### ISSUE TITLE
php 7

### ISSUE THREAD

**Issue by johnbfarmer** [phpwaymx/phpwaymx.github.io#11]

**Comment by dmouse** [comment]
Que de PHP 7, podrías hablar de esto @johnbfarmer?

**Comment by johnbfarmer** [comment]
jaja, no estaba ofreciendo a hablar. sé muy poquito de los cambios y quiero saber más.

**Comment by dmouse** [comment]
Ya hemos hablado de PHP 7 En la meetup de Diciembre. Cierro el issue
