### ISSUE TITLE
Twig Engine

### ISSUE THREAD

**Issue by dmouse** [phpwaymx/phpwaymx.github.io#4]
Hablar de los diferente Engines para hacer templating en php

**Comment by dmouse** [comment]
Propongo que en una charla hablemos de twig, y todas sus bondades

**Comment by eisenheimjelid** [comment]
¿Tu vas a dar la charla dmouse?... me interesa saber más del tema :+1:

**Comment by dmouse** [comment]
había un chavo interesado, ojala el pueda hacerlo, también hablar de smarty y por que PHP Template es del mal xD

**Comment by kouryuu** [comment]
Yo doy la charla sobre TWIG y Yeoman que permite hacer un scaffold desde CLI https://libraries.io/bower/twig-front.

**Comment by kouryuu** [comment]
Propuesta:
### Front-end PHP con TWIG
1. Intro
2. Generando un proyecto de cero con yeoman
3. Variables
4. Filtros
5. Estrucuras de control y loops
6. Macros y magia negra

y tal vez integración con Laravel,Silex,Symfony etc...

#### ¿Qué opinan?

**Comment by eisenheimjelid** [comment]
+1 :+1: solo te falta decir en cuanto tiempo das la charla, 1hr, 30min, 2.5hrs :P

**Comment by dmouse** [comment]
Todas las charlas son de 20 minutos =)

**Comment by dmouse** [comment]
Creo que en lugar de Macros y magia negra que sea algo de como usar extend, block include y esas cosas :heart: de twig :P

**Comment by kouryuu** [comment]
Si tienes razón pensé en extend y block, aunque quería el *Wow factor* de las macros que son muy poderosas.

**Comment by dmouse** [comment]
Checa si te da chance en 20 minutos dar todo eso

**Comment by kouryuu** [comment]
Pues no quiero meterme demasiado en detalles... mi idea es dar lo básico (entonces me toma menos de 5 min cada tema)  y supongo se abre un espacio de 5 o 10 minutos para preguntas ¿no?

**Comment by dmouse** [comment]
Si habrá un espacio de 10 minutos para preguntas

**Comment by jfreites** [comment]
+1

**Comment by iBet7o** [comment]
+1

**Comment by eisenheimjelid** [comment]
+1

**Comment by juanCarlos123** [comment]
+1

**Comment by kouryuu** [comment]
BTW si alguien me puede prestar adaptador para conectar mi Mac al proyector , le agradeceria enormemente. :smile:
