### ISSUE TITLE
APM's y Apdex

### ISSUE THREAD

**Issue by eisenheimjelid** [phpwaymx/phpwaymx.github.io#7]
¿Alguien conoce el índice APDEX? Para medir El rendimiento de un aplicativo Web y poder compararlo con otros, en función de la satisfacción del usuario. Adicional, los APM's (Application Performance Management) no solo sirven para mantener un control estricto sobre los recursos y un registro de errores, si no también para apoyar el desarrollo desde el backend y hasta en el frontend.
¿Qué les parece una platica sobre este tipo de herramientas?, en particular he hablado sobre NewRelic en otros foros.

**Comment by dmouse** [comment]
+1

**Comment by jfreites** [comment]
+1

**Comment by dubrox** [comment]
+1

**Comment by dmouse** [comment]
@eisenheimjelid tu la quieres dar para la siguiente meetup?

**Comment by eisenheimjelid** [comment]
Si claro, la propuesta era por eso mismo :P porque yo puedo dar la charla

**Comment by iBet7o** [comment]
+1

**Comment by hectorip** [comment]
+1

**Comment by kouryuu** [comment]
+1

**Comment by juanCarlos123** [comment]
+1

**Comment by felixsalgado** [comment]
hola nececito ayuda con el etiquetado de las imagenes

**Comment by eisenheimjelid** [comment]
Hola! @felixsalgado  ¿todo bien? alguien te respondió? ... ¿cual etiquetado en que imágenes? :P creo que este no es el lugar correcto para preguntar, pero con todo gusto puedo intentar ayudar.

**Comment by felixsalgado** [comment]
siii nececito ayuda para georeferenciar las imagenes capturadas desde mi camra canon 

Date: Tue, 8 Dec 2015 09:34:43 -0800

**Comment by felixsalgado** [comment]
yo le doy ctrl + f en el mision planner y le doy en la primera opcion tengo los logs y las imagenes pero no se como georeferenciar

**Comment by felixsalgado** [comment]
es sobre aereofotogrametria

**Comment by felixsalgado** [comment]
estoy en el lugar equivocado :P

**Comment by eisenheimjelid** [comment]
Ok!, bueno @felixsalgado suerte ... de momento creo que este issue ya debe estar cerrado.
