### ISSUE TITLE
Silex,  introducción y tips para escalar aplicaciones

### ISSUE THREAD

**Issue by gnuget** [phpwaymx/phpwaymx.github.io#8]
Ultimamente he estado jugando con Silex para construir una API sencilla, y he estado experiementando con el framework de tal manera que  lo podamos usar para escalar de uan API sencilla a un proyecto mucho mas grande. 

Para mi es un topico bastante interesante, como silex mas allá de ser un framework para cosas sencillas es un framework que te da una extraordinaria flexibilidad para escalar las aplicaciones como tu quieras.

**Comment by dmouse** [comment]
+1

**Comment by gnuget** [comment]
@dmouse  Si, :D

**Comment by mxcoder** [comment]
+1

**Comment by ivanm** [comment]
+1

**Comment by AldoMX** [comment]
+1 justo estoy dando mis primeros pasos en Silex
