### ISSUE TITLE
API's

### ISSUE THREAD

**Issue by joecohens** [phpwaymx/phpwaymx.github.io#9]
La idea sería poder ver todo lo relacionado a la creación de API's

- [ ] Resources
- [ ] Exceptions
- [ ] Authentication (Basic, Token, Oauth, JWT)
- [ ] Routes
- [x] Responses
- [x] Requests

**Comment by kouryuu** [comment]
+1

**Comment by joecohens** [comment]
No vi que ya estaba esté issue https://github.com/phpwaymx/phpwaymx.github.io/issues/2, muevo esto para allá
